export { generateEmbedding } from './services/generateEmbedding';
export { compareEmbeddings } from './services/compareEmbeddings';
export { recognizeFace } from './services/recognizeFace';
export { verifyIdentity } from './services/verifyIdentity';
export { cosineSimilarity } from './similarity/cosineSimilarity';
export { euclideanDistance } from './similarity/euclideanDistance';
export { isMatch, SIMILARITY_THRESHOLD } from './similarity/similarityThreshold';
export { getCachedEmbedding, setCachedEmbedding, invalidateCache, clearCache } from './cache/embeddingCache';
export { cacheManager } from './cache/cacheManager';
export { CACHE_POLICY } from './cache/cachePolicy';
export type { EmbeddingResult, ComparisonResult, CacheEntry } from './types/recognition.types';
