export enum SDKErrorCode {
  MODEL_LOAD_FAILED = 'MODEL_LOAD_FAILED',
  SDK_NOT_INITIALIZED = 'SDK_NOT_INITIALIZED',
  FRAME_TOO_BLURRY = 'FRAME_TOO_BLURRY',
  FRAME_TOO_DARK = 'FRAME_TOO_DARK',
  FACE_TOO_SMALL = 'FACE_TOO_SMALL',
  MULTIPLE_FACES = 'MULTIPLE_FACES',
  NO_FACE_DETECTED = 'NO_FACE_DETECTED',
  LIVENESS_FAILED = 'LIVENESS_FAILED',
  LIVENESS_TIMEOUT = 'LIVENESS_TIMEOUT',
  USER_NOT_ENROLLED = 'USER_NOT_ENROLLED',
  DUPLICATE_ENROLLMENT = 'DUPLICATE_ENROLLMENT',
  INFERENCE_FAILED = 'INFERENCE_FAILED',
  THERMAL_THROTTLE = 'THERMAL_THROTTLE',
  GPS_UNAVAILABLE = 'GPS_UNAVAILABLE',
  GPS_SPOOFED = 'GPS_SPOOFED',
}

export enum SDKModule {
  SDK = 'SDK',
  ENGINE = 'ENGINE',
  DETECTION = 'DETECTION',
  LANDMARKS = 'LANDMARKS',
  LIVENESS = 'LIVENESS',
  RECOGNITION = 'RECOGNITION',
  VALIDATION = 'VALIDATION',
  GPS = 'GPS',
  ANTISPOOF = 'ANTISPOOF',
}
