export { computeEAR } from './analysis/eyeAspectRatio';
export { computeMAR } from './analysis/mouthRatio';
export { analyzeMovement } from './analysis/movementAnalysis';
export { checkMotionConsistency } from './analysis/motionConsistency';
export { analyzePose } from './analysis/poseAnalysis';
export { evaluateBlinkChallenge } from './challenges/blinkChallenge';
export { evaluateSmileChallenge } from './challenges/smileChallenge';
export { evaluateHeadTurnChallenge } from './challenges/headTurnChallenge';
export { shuffleChallenges } from './challenges/randomChallenge';
export { challengeSequencer } from './challenges/challengeSequencer';
export { validateBlink } from './validators/blinkValidator';
export { validateSmile } from './validators/smileValidator';
export { validatePose } from './validators/poseValidator';
export { validateLivenessChallenge } from './validators/livenessValidator';
export { computeOverallLivenessScore } from './scoring/livenessScore';
export { computeConfidenceScore } from './scoring/confidenceScore';
export { computeChallengeScore } from './scoring/challengeScore';
export type { EARResult, MARResult, ChallengeSessionState, LivenessChallengeResult } from './types/liveness.types';
